#!/bin/sh
# formats `cmus-remote -Q` in nice way

CMUSOUT="$(cmus-remote -Q)"

cmusopt() {
   cmus-remote -Q \
     | grep -e "$1" \
     | sed "s/$1 //"
}

artist() {
   cmusopt artist | sed 's/tag //'
}

title() {
   cmusopt title | sed 's/tag //;'
}

album() {
   cmusopt album | sed 's/tag //;'
}

_date() {
   cmusopt date | sed 's/tag //;'
}

status() {
   cmusopt status 
}

sec_to_min() {
   D="$1"
   MIN="$(echo $D/60%60 | bc)"
   SEC="$(echo $D%60 | bc)"
   echo "$MIN:$SEC" | awk -F: '{printf("%02d:%02d", $1, $2)}'
}

duration() {
   sec_to_min "$(cmusopt duration)"
}

position() {
   sec_to_min "$(cmusopt position)"
}

echo "$(status): $(artist) - $(title) ($(_date)) $(position)/$(duration)"
